using Microsoft.EntityFrameworkCore.Migrations;

// <auto-generated />
// Purpose: Applies and rolls back the initial authoritative control.db schema generated from the accepted S03-B physical model.
#pragma warning disable IDE0161, CA1861
#nullable disable

namespace RagChallenge.Infrastructure.Persistence.Migrations.Control
{
    /// <inheritdoc />
    public partial class InitialControlPlane : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "content_objects",
                columns: table => new
                {
                    content_sha256 = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    byte_length = table.Column<long>(type: "INTEGER", nullable: false),
                    registered_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_content_objects", x => x.content_sha256);
                    table.CheckConstraint("ck_content_objects_length", "byte_length > 0");
                    table.CheckConstraint("ck_content_objects_registered_utc", "length(registered_at_utc) = 33 AND substr(registered_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_content_objects_sha", "length(content_sha256) = 64 AND content_sha256 NOT GLOB '*[^0-9a-f]*'");
                });

            migrationBuilder.CreateTable(
                name: "corpora",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    corpus_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    created_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_corpora", x => x.corpus_id);
                    table.CheckConstraint("ck_corpora_created_utc", "length(created_at_utc) = 33 AND substr(created_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_corpora_id", "length(corpus_id) BETWEEN 1 AND 128 AND corpus_id GLOB '[A-Za-z0-9]*' AND corpus_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_corpora_revision", "corpus_revision > 0");
                });

            migrationBuilder.CreateTable(
                name: "admin_operations",
                columns: table => new
                {
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    operation_kind = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    status = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    expected_revision = table.Column<long>(type: "INTEGER", nullable: true),
                    result_revision = table.Column<long>(type: "INTEGER", nullable: true),
                    requested_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    completed_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_admin_operations", x => x.operation_id);
                    table.CheckConstraint("ck_admin_operations_completed_utc", "completed_at_utc IS NULL OR length(completed_at_utc) = 33 AND substr(completed_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_admin_operations_expected", "expected_revision IS NULL OR expected_revision >= 0");
                    table.CheckConstraint("ck_admin_operations_id", "length(operation_id) BETWEEN 1 AND 128 AND operation_id GLOB '[A-Za-z0-9]*' AND operation_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_admin_operations_requested_utc", "length(requested_at_utc) = 33 AND substr(requested_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_admin_operations_result", "result_revision IS NULL OR result_revision > 0");
                    table.CheckConstraint("ck_admin_operations_status", "status IN ('InProgress', 'Applied', 'Rejected', 'Failed')");
                    table.ForeignKey(
                        name: "FK_admin_operations_corpora_corpus_id",
                        column: x => x.corpus_id,
                        principalTable: "corpora",
                        principalColumn: "corpus_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "database_categories",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    category_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    display_name = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_database_categories", x => new { x.corpus_id, x.category_id });
                    table.CheckConstraint("ck_database_categories_id", "length(category_id) BETWEEN 1 AND 128 AND category_id GLOB '[A-Za-z0-9]*' AND category_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_database_categories_name", "length(display_name) BETWEEN 1 AND 256");
                    table.ForeignKey(
                        name: "FK_database_categories_corpora_corpus_id",
                        column: x => x.corpus_id,
                        principalTable: "corpora",
                        principalColumn: "corpus_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "database_product_revisions",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    display_name = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    status = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_database_product_revisions", x => new { x.corpus_id, x.product_id, x.product_revision });
                    table.CheckConstraint("ck_database_products_id", "length(product_id) BETWEEN 1 AND 128 AND product_id GLOB '[A-Za-z0-9]*' AND product_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_database_products_name", "length(display_name) BETWEEN 1 AND 256");
                    table.CheckConstraint("ck_database_products_revision", "product_revision > 0");
                    table.CheckConstraint("ck_database_products_status", "status IN ('Candidate', 'Active', 'Deactivated', 'Removed')");
                    table.ForeignKey(
                        name: "FK_database_product_revisions_corpora_corpus_id",
                        column: x => x.corpus_id,
                        principalTable: "corpora",
                        principalColumn: "corpus_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "observation_journal_heads",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    journal_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    row_revision = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_observation_journal_heads", x => x.corpus_id);
                    table.CheckConstraint("ck_observation_heads_revision", "journal_revision > 0");
                    table.CheckConstraint("ck_observation_heads_row_revision", "row_revision > 0");
                    table.ForeignKey(
                        name: "FK_observation_journal_heads_corpora_corpus_id",
                        column: x => x.corpus_id,
                        principalTable: "corpora",
                        principalColumn: "corpus_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "official_source_registrations",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    registration_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    registration_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    product_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    document_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_adapter_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    canonical_https_url = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    status = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_official_source_registrations", x => new { x.corpus_id, x.registration_id, x.registration_revision });
                    table.CheckConstraint("ck_source_registrations_https", "canonical_https_url GLOB 'https://*' AND instr(canonical_https_url, '#') = 0");
                    table.CheckConstraint("ck_source_registrations_id", "length(registration_id) BETWEEN 1 AND 128 AND registration_id GLOB '[A-Za-z0-9]*' AND registration_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_source_registrations_revision", "registration_revision > 0");
                    table.CheckConstraint("ck_source_registrations_status", "status IN ('Candidate', 'Active', 'Deactivated', 'Removed')");
                    table.ForeignKey(
                        name: "FK_official_source_registrations_corpora_corpus_id",
                        column: x => x.corpus_id,
                        principalTable: "corpora",
                        principalColumn: "corpus_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "audit_events",
                columns: table => new
                {
                    audit_event_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    event_type = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    occurred_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    details_digest = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_audit_events", x => x.audit_event_id);
                    table.CheckConstraint("ck_audit_events_details", "length(details_digest) = 64 AND details_digest NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_audit_events_id", "length(audit_event_id) BETWEEN 1 AND 128 AND audit_event_id GLOB '[A-Za-z0-9]*' AND audit_event_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_audit_events_occurred_utc", "length(occurred_at_utc) = 33 AND substr(occurred_at_utc, -6) = '+00:00'");
                    table.ForeignKey(
                        name: "FK_audit_events_admin_operations_operation_id",
                        column: x => x.operation_id,
                        principalTable: "admin_operations",
                        principalColumn: "operation_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "catalogue_revisions",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    catalogue_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    created_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_catalogue_revisions", x => new { x.corpus_id, x.catalogue_revision });
                    table.CheckConstraint("ck_catalogue_revisions_created_utc", "length(created_at_utc) = 33 AND substr(created_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_catalogue_revisions_revision", "catalogue_revision > 0");
                    table.ForeignKey(
                        name: "FK_catalogue_revisions_admin_operations_operation_id",
                        column: x => x.operation_id,
                        principalTable: "admin_operations",
                        principalColumn: "operation_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_catalogue_revisions_corpora_corpus_id",
                        column: x => x.corpus_id,
                        principalTable: "corpora",
                        principalColumn: "corpus_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "recovery_leases",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    lease_name = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    acquired_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    expires_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_recovery_leases", x => new { x.corpus_id, x.lease_name });
                    table.CheckConstraint("ck_recovery_leases_acquired_utc", "length(acquired_at_utc) = 33 AND substr(acquired_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_recovery_leases_expires_utc", "length(expires_at_utc) = 33 AND substr(expires_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_recovery_leases_name", "length(lease_name) BETWEEN 1 AND 64");
                    table.CheckConstraint("ck_recovery_leases_time_order", "expires_at_utc > acquired_at_utc");
                    table.ForeignKey(
                        name: "FK_recovery_leases_admin_operations_operation_id",
                        column: x => x.operation_id,
                        principalTable: "admin_operations",
                        principalColumn: "operation_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "database_product_categories",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    category_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_database_product_categories", x => new { x.corpus_id, x.product_id, x.product_revision, x.category_id });
                    table.ForeignKey(
                        name: "FK_database_product_categories_database_categories_corpus_id_category_id",
                        columns: x => new { x.corpus_id, x.category_id },
                        principalTable: "database_categories",
                        principalColumns: new[] { "corpus_id", "category_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_database_product_categories_database_product_revisions_corpus_id_product_id_product_revision",
                        columns: x => new { x.corpus_id, x.product_id, x.product_revision },
                        principalTable: "database_product_revisions",
                        principalColumns: new[] { "corpus_id", "product_id", "product_revision" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "document_versions",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    document_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    document_version = table.Column<long>(type: "INTEGER", nullable: false),
                    product_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    document_format = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    content_language = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    content_sha256 = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    byte_length = table.Column<long>(type: "INTEGER", nullable: false),
                    media_type = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_adapter_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_trust_class = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    official_registration_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY"),
                    official_snapshot_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_document_versions", x => new { x.corpus_id, x.document_id, x.document_version });
                    table.CheckConstraint("ck_document_versions_format", "document_format IN ('Pdf', 'Csv')");
                    table.CheckConstraint("ck_document_versions_id", "length(document_id) BETWEEN 1 AND 128 AND document_id GLOB '[A-Za-z0-9]*' AND document_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_document_versions_language", "content_language IN ('pt-BR', 'en-GB')");
                    table.CheckConstraint("ck_document_versions_length", "byte_length > 0");
                    table.CheckConstraint("ck_document_versions_media_type", "length(media_type) BETWEEN 1 AND 128");
                    table.CheckConstraint("ck_document_versions_source_identity", "(source_trust_class = 'LocalAuthorised' AND official_registration_id IS NULL AND official_snapshot_id IS NULL) OR (source_trust_class = 'OfficialExternal' AND official_registration_id IS NOT NULL AND official_snapshot_id IS NOT NULL)");
                    table.CheckConstraint("ck_document_versions_trust", "source_trust_class IN ('LocalAuthorised', 'OfficialExternal')");
                    table.CheckConstraint("ck_document_versions_version", "document_version > 0");
                    table.ForeignKey(
                        name: "FK_document_versions_content_objects_content_sha256",
                        column: x => x.content_sha256,
                        principalTable: "content_objects",
                        principalColumn: "content_sha256",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_document_versions_database_product_revisions_corpus_id_product_id_product_revision",
                        columns: x => new { x.corpus_id, x.product_id, x.product_revision },
                        principalTable: "database_product_revisions",
                        principalColumns: new[] { "corpus_id", "product_id", "product_revision" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "official_source_snapshots",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    snapshot_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    registration_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    registration_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    content_sha256 = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    byte_length = table.Column<long>(type: "INTEGER", nullable: false),
                    media_type = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    retrieved_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_official_source_snapshots", x => new { x.corpus_id, x.snapshot_id });
                    table.CheckConstraint("ck_source_snapshots_id", "length(snapshot_id) BETWEEN 1 AND 128 AND snapshot_id GLOB '[A-Za-z0-9]*' AND snapshot_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_source_snapshots_length", "byte_length > 0");
                    table.CheckConstraint("ck_source_snapshots_media_type", "length(media_type) BETWEEN 1 AND 128");
                    table.CheckConstraint("ck_source_snapshots_retrieved_utc", "length(retrieved_at_utc) = 33 AND substr(retrieved_at_utc, -6) = '+00:00'");
                    table.ForeignKey(
                        name: "FK_official_source_snapshots_content_objects_content_sha256",
                        column: x => x.content_sha256,
                        principalTable: "content_objects",
                        principalColumn: "content_sha256",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_official_source_snapshots_official_source_registrations_corpus_id_registration_id_registration_revision",
                        columns: x => new { x.corpus_id, x.registration_id, x.registration_revision },
                        principalTable: "official_source_registrations",
                        principalColumns: new[] { "corpus_id", "registration_id", "registration_revision" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "catalogue_heads",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    catalogue_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    row_revision = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_catalogue_heads", x => x.corpus_id);
                    table.CheckConstraint("ck_catalogue_heads_revision", "catalogue_revision > 0");
                    table.CheckConstraint("ck_catalogue_heads_row_revision", "row_revision > 0");
                    table.ForeignKey(
                        name: "FK_catalogue_heads_catalogue_revisions_corpus_id_catalogue_revision",
                        columns: x => new { x.corpus_id, x.catalogue_revision },
                        principalTable: "catalogue_revisions",
                        principalColumns: new[] { "corpus_id", "catalogue_revision" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "catalogue_revision_products",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    catalogue_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    product_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_revision = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_catalogue_revision_products", x => new { x.corpus_id, x.catalogue_revision, x.product_id });
                    table.ForeignKey(
                        name: "FK_catalogue_revision_products_catalogue_revisions_corpus_id_catalogue_revision",
                        columns: x => new { x.corpus_id, x.catalogue_revision },
                        principalTable: "catalogue_revisions",
                        principalColumns: new[] { "corpus_id", "catalogue_revision" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_catalogue_revision_products_database_product_revisions_corpus_id_product_id_product_revision",
                        columns: x => new { x.corpus_id, x.product_id, x.product_revision },
                        principalTable: "database_product_revisions",
                        principalColumns: new[] { "corpus_id", "product_id", "product_revision" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "generation_manifests",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    index_generation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    candidate_build_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    manifest_schema_version = table.Column<int>(type: "INTEGER", nullable: false),
                    corpus_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    catalogue_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    active_document_set_digest = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_binding_set_digest = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    index_compatibility_key = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    generation_spec_digest = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    chunk_count = table.Column<long>(type: "INTEGER", nullable: false),
                    vector_count = table.Column<long>(type: "INTEGER", nullable: false),
                    logical_artifact_digest = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    generation_content_digest = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    finalised_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_generation_manifests", x => new { x.corpus_id, x.index_generation_id });
                    table.CheckConstraint("ck_generation_manifests_active_digest", "length(active_document_set_digest) = 64 AND active_document_set_digest NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_generation_manifests_candidate", "length(candidate_build_id) BETWEEN 1 AND 128 AND candidate_build_id GLOB '[A-Za-z0-9]*' AND candidate_build_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_generation_manifests_compatibility", "length(index_compatibility_key) = 64 AND index_compatibility_key NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_generation_manifests_content", "length(generation_content_digest) = 64 AND generation_content_digest NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_generation_manifests_counts", "chunk_count > 0 AND vector_count = chunk_count");
                    table.CheckConstraint("ck_generation_manifests_finalised_utc", "length(finalised_at_utc) = 33 AND substr(finalised_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_generation_manifests_id", "length(index_generation_id) = 71 AND substr(index_generation_id, 1, 7) = 'idxgen-' AND substr(index_generation_id, 8) NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_generation_manifests_identity", "index_generation_id = 'idxgen-' || generation_content_digest");
                    table.CheckConstraint("ck_generation_manifests_logical", "length(logical_artifact_digest) = 64 AND logical_artifact_digest NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_generation_manifests_revisions", "corpus_revision > 0 AND catalogue_revision > 0");
                    table.CheckConstraint("ck_generation_manifests_schema", "manifest_schema_version > 0");
                    table.CheckConstraint("ck_generation_manifests_source_digest", "length(source_binding_set_digest) = 64 AND source_binding_set_digest NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_generation_manifests_spec", "length(generation_spec_digest) = 64 AND generation_spec_digest NOT GLOB '*[^0-9a-f]*'");
                    table.ForeignKey(
                        name: "FK_generation_manifests_admin_operations_operation_id",
                        column: x => x.operation_id,
                        principalTable: "admin_operations",
                        principalColumn: "operation_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_generation_manifests_catalogue_revisions_corpus_id_catalogue_revision",
                        columns: x => new { x.corpus_id, x.catalogue_revision },
                        principalTable: "catalogue_revisions",
                        principalColumns: new[] { "corpus_id", "catalogue_revision" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_generation_manifests_corpora_corpus_id",
                        column: x => x.corpus_id,
                        principalTable: "corpora",
                        principalColumn: "corpus_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "catalogue_revision_documents",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    catalogue_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    document_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    document_version = table.Column<long>(type: "INTEGER", nullable: false),
                    status = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_catalogue_revision_documents", x => new { x.corpus_id, x.catalogue_revision, x.document_id, x.document_version });
                    table.CheckConstraint("ck_catalogue_revision_documents_status", "status IN ('Candidate', 'Active', 'Deactivated', 'Removed')");
                    table.ForeignKey(
                        name: "FK_catalogue_revision_documents_catalogue_revisions_corpus_id_catalogue_revision",
                        columns: x => new { x.corpus_id, x.catalogue_revision },
                        principalTable: "catalogue_revisions",
                        principalColumns: new[] { "corpus_id", "catalogue_revision" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_catalogue_revision_documents_document_versions_corpus_id_document_id_document_version",
                        columns: x => new { x.corpus_id, x.document_id, x.document_version },
                        principalTable: "document_versions",
                        principalColumns: new[] { "corpus_id", "document_id", "document_version" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "source_observations",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    observation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    registration_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    snapshot_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    journal_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    state = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    revalidated_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    max_age_seconds = table.Column<long>(type: "INTEGER", nullable: false),
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_source_observations", x => new { x.corpus_id, x.observation_id });
                    table.CheckConstraint("ck_source_observations_id", "length(observation_id) BETWEEN 1 AND 128 AND observation_id GLOB '[A-Za-z0-9]*' AND observation_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_source_observations_max_age", "max_age_seconds > 0");
                    table.CheckConstraint("ck_source_observations_revalidated_utc", "length(revalidated_at_utc) = 33 AND substr(revalidated_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_source_observations_revision", "journal_revision > 0");
                    table.CheckConstraint("ck_source_observations_state", "state IN ('Current', 'Stale', 'Withdrawn', 'Deactivated')");
                    table.ForeignKey(
                        name: "FK_source_observations_admin_operations_operation_id",
                        column: x => x.operation_id,
                        principalTable: "admin_operations",
                        principalColumn: "operation_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_source_observations_official_source_snapshots_corpus_id_snapshot_id",
                        columns: x => new { x.corpus_id, x.snapshot_id },
                        principalTable: "official_source_snapshots",
                        principalColumns: new[] { "corpus_id", "snapshot_id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "activation_records",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    record_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    previous_record_revision = table.Column<long>(type: "INTEGER", nullable: true),
                    index_generation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    catalogue_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    activation_binding_set_digest = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    mutation_kind = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    generation_activated_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    record_updated_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_activation_records", x => new { x.corpus_id, x.record_revision });
                    table.CheckConstraint("ck_activation_records_activated_utc", "length(generation_activated_at_utc) = 33 AND substr(generation_activated_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_activation_records_digest", "length(activation_binding_set_digest) = 64 AND activation_binding_set_digest NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_activation_records_kind", "mutation_kind IN ('Initial', 'Replacement', 'ObservationRebind', 'Rollback')");
                    table.CheckConstraint("ck_activation_records_lineage", "(record_revision = 1 AND previous_record_revision IS NULL) OR (record_revision > 1 AND previous_record_revision = record_revision - 1)");
                    table.CheckConstraint("ck_activation_records_revision", "record_revision > 0");
                    table.CheckConstraint("ck_activation_records_time_order", "record_updated_at_utc >= generation_activated_at_utc");
                    table.CheckConstraint("ck_activation_records_updated_utc", "length(record_updated_at_utc) = 33 AND substr(record_updated_at_utc, -6) = '+00:00'");
                    table.ForeignKey(
                        name: "FK_activation_records_activation_records_corpus_id_previous_record_revision",
                        columns: x => new { x.corpus_id, x.previous_record_revision },
                        principalTable: "activation_records",
                        principalColumns: new[] { "corpus_id", "record_revision" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_activation_records_admin_operations_operation_id",
                        column: x => x.operation_id,
                        principalTable: "admin_operations",
                        principalColumn: "operation_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_activation_records_catalogue_revisions_corpus_id_catalogue_revision",
                        columns: x => new { x.corpus_id, x.catalogue_revision },
                        principalTable: "catalogue_revisions",
                        principalColumns: new[] { "corpus_id", "catalogue_revision" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_activation_records_generation_manifests_corpus_id_index_generation_id",
                        columns: x => new { x.corpus_id, x.index_generation_id },
                        principalTable: "generation_manifests",
                        principalColumns: new[] { "corpus_id", "index_generation_id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "generation_manifest_bindings",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    index_generation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    document_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    document_version = table.Column<long>(type: "INTEGER", nullable: false),
                    product_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    document_format = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_adapter_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_trust_class = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    official_registration_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY"),
                    official_snapshot_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_generation_manifest_bindings", x => new { x.corpus_id, x.index_generation_id, x.document_id, x.document_version });
                    table.CheckConstraint("ck_generation_bindings_format", "document_format IN ('Pdf', 'Csv')");
                    table.CheckConstraint("ck_generation_bindings_source_identity", "(source_trust_class = 'LocalAuthorised' AND official_registration_id IS NULL AND official_snapshot_id IS NULL) OR (source_trust_class = 'OfficialExternal' AND official_registration_id IS NOT NULL AND official_snapshot_id IS NOT NULL)");
                    table.CheckConstraint("ck_generation_bindings_trust", "source_trust_class IN ('LocalAuthorised', 'OfficialExternal')");
                    table.ForeignKey(
                        name: "FK_generation_manifest_bindings_document_versions_corpus_id_document_id_document_version",
                        columns: x => new { x.corpus_id, x.document_id, x.document_version },
                        principalTable: "document_versions",
                        principalColumns: new[] { "corpus_id", "document_id", "document_version" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_generation_manifest_bindings_generation_manifests_corpus_id_index_generation_id",
                        columns: x => new { x.corpus_id, x.index_generation_id },
                        principalTable: "generation_manifests",
                        principalColumns: new[] { "corpus_id", "index_generation_id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "generation_retention",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    index_generation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    protection_role = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    retain_until_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    recorded_at_utc = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    operation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_generation_retention", x => new { x.corpus_id, x.index_generation_id });
                    table.CheckConstraint("ck_generation_retention_recorded_utc", "length(recorded_at_utc) = 33 AND substr(recorded_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_generation_retention_role", "protection_role IN ('Active', 'Previous', 'Hold')");
                    table.CheckConstraint("ck_generation_retention_time_order", "retain_until_utc >= recorded_at_utc");
                    table.CheckConstraint("ck_generation_retention_until_utc", "length(retain_until_utc) = 33 AND substr(retain_until_utc, -6) = '+00:00'");
                    table.ForeignKey(
                        name: "FK_generation_retention_admin_operations_operation_id",
                        column: x => x.operation_id,
                        principalTable: "admin_operations",
                        principalColumn: "operation_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_generation_retention_generation_manifests_corpus_id_index_generation_id",
                        columns: x => new { x.corpus_id, x.index_generation_id },
                        principalTable: "generation_manifests",
                        principalColumns: new[] { "corpus_id", "index_generation_id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "activation_bindings",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    record_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    document_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    document_version = table.Column<long>(type: "INTEGER", nullable: false),
                    product_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    product_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    document_format = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_adapter_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    source_trust_class = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    official_registration_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY"),
                    official_snapshot_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY"),
                    source_observation_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: true, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_activation_bindings", x => new { x.corpus_id, x.record_revision, x.document_id, x.document_version });
                    table.CheckConstraint("ck_activation_bindings_format", "document_format IN ('Pdf', 'Csv')");
                    table.CheckConstraint("ck_activation_bindings_source_identity", "(source_trust_class = 'LocalAuthorised' AND official_registration_id IS NULL AND official_snapshot_id IS NULL AND source_observation_id IS NULL) OR (source_trust_class = 'OfficialExternal' AND official_registration_id IS NOT NULL AND official_snapshot_id IS NOT NULL AND source_observation_id IS NOT NULL)");
                    table.CheckConstraint("ck_activation_bindings_trust", "source_trust_class IN ('LocalAuthorised', 'OfficialExternal')");
                    table.ForeignKey(
                        name: "FK_activation_bindings_activation_records_corpus_id_record_revision",
                        columns: x => new { x.corpus_id, x.record_revision },
                        principalTable: "activation_records",
                        principalColumns: new[] { "corpus_id", "record_revision" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_activation_bindings_document_versions_corpus_id_document_id_document_version",
                        columns: x => new { x.corpus_id, x.document_id, x.document_version },
                        principalTable: "document_versions",
                        principalColumns: new[] { "corpus_id", "document_id", "document_version" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_activation_bindings_source_observations_corpus_id_source_observation_id",
                        columns: x => new { x.corpus_id, x.source_observation_id },
                        principalTable: "source_observations",
                        principalColumns: new[] { "corpus_id", "observation_id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "activation_heads",
                columns: table => new
                {
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false, collation: "BINARY"),
                    record_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    row_revision = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_activation_heads", x => x.corpus_id);
                    table.CheckConstraint("ck_activation_heads_revision", "record_revision > 0");
                    table.CheckConstraint("ck_activation_heads_row_revision", "row_revision > 0");
                    table.ForeignKey(
                        name: "FK_activation_heads_activation_records_corpus_id_record_revision",
                        columns: x => new { x.corpus_id, x.record_revision },
                        principalTable: "activation_records",
                        principalColumns: new[] { "corpus_id", "record_revision" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_activation_bindings_corpus_id_document_id_document_version",
                table: "activation_bindings",
                columns: new[] { "corpus_id", "document_id", "document_version" });

            migrationBuilder.CreateIndex(
                name: "IX_activation_bindings_corpus_id_source_observation_id",
                table: "activation_bindings",
                columns: new[] { "corpus_id", "source_observation_id" });

            migrationBuilder.CreateIndex(
                name: "IX_activation_heads_corpus_id_record_revision",
                table: "activation_heads",
                columns: new[] { "corpus_id", "record_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_activation_records_corpus_id_catalogue_revision",
                table: "activation_records",
                columns: new[] { "corpus_id", "catalogue_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_activation_records_corpus_id_index_generation_id",
                table: "activation_records",
                columns: new[] { "corpus_id", "index_generation_id" });

            migrationBuilder.CreateIndex(
                name: "IX_activation_records_corpus_id_previous_record_revision",
                table: "activation_records",
                columns: new[] { "corpus_id", "previous_record_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_activation_records_operation_id",
                table: "activation_records",
                column: "operation_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_admin_operations_corpus_id",
                table: "admin_operations",
                column: "corpus_id");

            migrationBuilder.CreateIndex(
                name: "IX_audit_events_corpus_id_occurred_at_utc",
                table: "audit_events",
                columns: new[] { "corpus_id", "occurred_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_audit_events_operation_id",
                table: "audit_events",
                column: "operation_id");

            migrationBuilder.CreateIndex(
                name: "IX_catalogue_heads_corpus_id_catalogue_revision",
                table: "catalogue_heads",
                columns: new[] { "corpus_id", "catalogue_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_catalogue_revision_documents_corpus_id_document_id_document_version",
                table: "catalogue_revision_documents",
                columns: new[] { "corpus_id", "document_id", "document_version" });

            migrationBuilder.CreateIndex(
                name: "ux_catalogue_revision_documents_one_active",
                table: "catalogue_revision_documents",
                columns: new[] { "corpus_id", "catalogue_revision", "document_id" },
                unique: true,
                filter: "status = 'Active'");

            migrationBuilder.CreateIndex(
                name: "IX_catalogue_revision_products_corpus_id_product_id_product_revision",
                table: "catalogue_revision_products",
                columns: new[] { "corpus_id", "product_id", "product_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_catalogue_revisions_operation_id",
                table: "catalogue_revisions",
                column: "operation_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_database_product_categories_corpus_id_category_id",
                table: "database_product_categories",
                columns: new[] { "corpus_id", "category_id" });

            migrationBuilder.CreateIndex(
                name: "IX_document_versions_content_sha256",
                table: "document_versions",
                column: "content_sha256");

            migrationBuilder.CreateIndex(
                name: "IX_document_versions_corpus_id_product_id_product_revision",
                table: "document_versions",
                columns: new[] { "corpus_id", "product_id", "product_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_generation_manifest_bindings_corpus_id_document_id_document_version",
                table: "generation_manifest_bindings",
                columns: new[] { "corpus_id", "document_id", "document_version" });

            migrationBuilder.CreateIndex(
                name: "IX_generation_manifests_corpus_id_candidate_build_id",
                table: "generation_manifests",
                columns: new[] { "corpus_id", "candidate_build_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_generation_manifests_corpus_id_catalogue_revision",
                table: "generation_manifests",
                columns: new[] { "corpus_id", "catalogue_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_generation_manifests_index_generation_id",
                table: "generation_manifests",
                column: "index_generation_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_generation_manifests_operation_id",
                table: "generation_manifests",
                column: "operation_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_generation_retention_operation_id",
                table: "generation_retention",
                column: "operation_id");

            migrationBuilder.CreateIndex(
                name: "ux_generation_retention_previous",
                table: "generation_retention",
                column: "corpus_id",
                unique: true,
                filter: "protection_role = 'Previous'");

            migrationBuilder.CreateIndex(
                name: "IX_official_source_snapshots_content_sha256",
                table: "official_source_snapshots",
                column: "content_sha256");

            migrationBuilder.CreateIndex(
                name: "IX_official_source_snapshots_corpus_id_registration_id_registration_revision",
                table: "official_source_snapshots",
                columns: new[] { "corpus_id", "registration_id", "registration_revision" });

            migrationBuilder.CreateIndex(
                name: "IX_recovery_leases_operation_id",
                table: "recovery_leases",
                column: "operation_id");

            migrationBuilder.CreateIndex(
                name: "IX_source_observations_corpus_id_journal_revision",
                table: "source_observations",
                columns: new[] { "corpus_id", "journal_revision" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_source_observations_corpus_id_snapshot_id",
                table: "source_observations",
                columns: new[] { "corpus_id", "snapshot_id" });

            migrationBuilder.CreateIndex(
                name: "IX_source_observations_operation_id",
                table: "source_observations",
                column: "operation_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "activation_bindings");

            migrationBuilder.DropTable(
                name: "activation_heads");

            migrationBuilder.DropTable(
                name: "audit_events");

            migrationBuilder.DropTable(
                name: "catalogue_heads");

            migrationBuilder.DropTable(
                name: "catalogue_revision_documents");

            migrationBuilder.DropTable(
                name: "catalogue_revision_products");

            migrationBuilder.DropTable(
                name: "database_product_categories");

            migrationBuilder.DropTable(
                name: "generation_manifest_bindings");

            migrationBuilder.DropTable(
                name: "generation_retention");

            migrationBuilder.DropTable(
                name: "observation_journal_heads");

            migrationBuilder.DropTable(
                name: "recovery_leases");

            migrationBuilder.DropTable(
                name: "source_observations");

            migrationBuilder.DropTable(
                name: "activation_records");

            migrationBuilder.DropTable(
                name: "database_categories");

            migrationBuilder.DropTable(
                name: "document_versions");

            migrationBuilder.DropTable(
                name: "official_source_snapshots");

            migrationBuilder.DropTable(
                name: "generation_manifests");

            migrationBuilder.DropTable(
                name: "database_product_revisions");

            migrationBuilder.DropTable(
                name: "content_objects");

            migrationBuilder.DropTable(
                name: "official_source_registrations");

            migrationBuilder.DropTable(
                name: "catalogue_revisions");

            migrationBuilder.DropTable(
                name: "admin_operations");

            migrationBuilder.DropTable(
                name: "corpora");
        }
    }
}
