using Microsoft.EntityFrameworkCore.Migrations;

// <auto-generated />
// Purpose: Applies and rolls back the initial derived vectors.db schema generated from the accepted S03-B physical model.
#pragma warning disable IDE0161, CA1861
#nullable disable

namespace RagChallenge.Infrastructure.Persistence.Migrations.Vector
{
    /// <inheritdoc />
    public partial class InitialVectorStore : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "vector_builds",
                columns: table => new
                {
                    candidate_build_id = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    corpus_id = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    status = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    index_generation_id = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: true, collation: "BINARY"),
                    index_compatibility_key = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    vector_dimensions = table.Column<int>(type: "INTEGER", nullable: false),
                    expected_chunk_count = table.Column<long>(type: "INTEGER", nullable: false),
                    created_at_utc = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    validated_at_utc = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: true, collation: "BINARY")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_vector_builds", x => x.candidate_build_id);
                    table.CheckConstraint("ck_vector_builds_candidate_id", "length(candidate_build_id) BETWEEN 1 AND 128 AND candidate_build_id GLOB '[A-Za-z0-9]*' AND candidate_build_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_vector_builds_chunk_count", "expected_chunk_count > 0");
                    table.CheckConstraint("ck_vector_builds_compatibility", "length(index_compatibility_key) = 64 AND index_compatibility_key NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_vector_builds_corpus_id", "length(corpus_id) BETWEEN 1 AND 128 AND corpus_id GLOB '[A-Za-z0-9]*' AND corpus_id NOT GLOB '*[^A-Za-z0-9._:-]*'");
                    table.CheckConstraint("ck_vector_builds_created_utc", "length(created_at_utc) = 33 AND substr(created_at_utc, -6) = '+00:00'");
                    table.CheckConstraint("ck_vector_builds_dimensions", "vector_dimensions BETWEEN 1 AND 65536");
                    table.CheckConstraint("ck_vector_builds_generation_id", "index_generation_id IS NULL OR length(index_generation_id) = 71 AND substr(index_generation_id, 1, 7) = 'idxgen-' AND substr(index_generation_id, 8) NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_vector_builds_generation_state", "(status = 'Validated' AND index_generation_id IS NOT NULL AND validated_at_utc IS NOT NULL) OR (status <> 'Validated' AND index_generation_id IS NULL AND validated_at_utc IS NULL)");
                    table.CheckConstraint("ck_vector_builds_status", "status IN ('Candidate', 'Validated', 'Failed')");
                    table.CheckConstraint("ck_vector_builds_validated_utc", "validated_at_utc IS NULL OR length(validated_at_utc) = 33 AND substr(validated_at_utc, -6) = '+00:00'");
                });

            migrationBuilder.CreateTable(
                name: "vector_chunks",
                columns: table => new
                {
                    candidate_build_id = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    chunk_ordinal = table.Column<long>(type: "INTEGER", nullable: false),
                    document_id = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    document_version = table.Column<long>(type: "INTEGER", nullable: false),
                    chunk_digest = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    chunk_text = table.Column<string>(type: "TEXT", maxLength: 1048576, nullable: false, collation: "BINARY"),
                    vector = table.Column<byte[]>(type: "BLOB", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_vector_chunks", x => new { x.candidate_build_id, x.chunk_ordinal });
                    table.CheckConstraint("ck_vector_chunks_digest", "length(chunk_digest) = 64 AND chunk_digest NOT GLOB '*[^0-9a-f]*'");
                    table.CheckConstraint("ck_vector_chunks_document_version", "document_version > 0");
                    table.CheckConstraint("ck_vector_chunks_ordinal", "chunk_ordinal >= 0");
                    table.CheckConstraint("ck_vector_chunks_text", "length(chunk_text) BETWEEN 1 AND 1048576");
                    table.CheckConstraint("ck_vector_chunks_vector", "length(vector) > 0 AND length(vector) % 4 = 0");
                    table.ForeignKey(
                        name: "FK_vector_chunks_vector_builds_candidate_build_id",
                        column: x => x.candidate_build_id,
                        principalTable: "vector_builds",
                        principalColumn: "candidate_build_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_vector_builds_index_generation_id",
                table: "vector_builds",
                column: "index_generation_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_vector_chunks_candidate_build_id_document_id_document_version_chunk_digest",
                table: "vector_chunks",
                columns: new[] { "candidate_build_id", "document_id", "document_version", "chunk_digest" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "vector_chunks");

            migrationBuilder.DropTable(
                name: "vector_builds");
        }
    }
}
