// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RagChallenge.Infrastructure.Persistence;

#nullable disable

namespace RagChallenge.Infrastructure.Persistence.Migrations.Vector
{
    [DbContext(typeof(VectorStoreDbContext))]
    partial class VectorStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RagChallenge.Infrastructure.Persistence.VectorBuildRow", b =>
                {
                    b.Property<string>("CandidateBuildId")
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_build_id")
                        .UseCollation("BINARY");

                    b.Property<string>("CorpusId")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("corpus_id")
                        .UseCollation("BINARY");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .UseCollation("BINARY");

                    b.Property<long>("ExpectedChunkCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expected_chunk_count");

                    b.Property<string>("IndexCompatibilityKey")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("index_compatibility_key")
                        .UseCollation("BINARY");

                    b.Property<string>("IndexGenerationId")
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("index_generation_id")
                        .UseCollation("BINARY");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("status")
                        .UseCollation("BINARY");

                    b.Property<string>("ValidatedAtUtc")
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("validated_at_utc")
                        .UseCollation("BINARY");

                    b.Property<int>("VectorDimensions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vector_dimensions");

                    b.HasKey("CandidateBuildId");

                    b.HasIndex("IndexGenerationId")
                        .IsUnique();

                    b.ToTable("vector_builds", null, t =>
                        {
                            t.HasCheckConstraint("ck_vector_builds_candidate_id", "length(candidate_build_id) BETWEEN 1 AND 128 AND candidate_build_id GLOB '[A-Za-z0-9]*' AND candidate_build_id NOT GLOB '*[^A-Za-z0-9._:-]*'");

                            t.HasCheckConstraint("ck_vector_builds_chunk_count", "expected_chunk_count > 0");

                            t.HasCheckConstraint("ck_vector_builds_compatibility", "length(index_compatibility_key) = 64 AND index_compatibility_key NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("ck_vector_builds_corpus_id", "length(corpus_id) BETWEEN 1 AND 128 AND corpus_id GLOB '[A-Za-z0-9]*' AND corpus_id NOT GLOB '*[^A-Za-z0-9._:-]*'");

                            t.HasCheckConstraint("ck_vector_builds_created_utc", "length(created_at_utc) = 33 AND substr(created_at_utc, -6) = '+00:00'");

                            t.HasCheckConstraint("ck_vector_builds_dimensions", "vector_dimensions BETWEEN 1 AND 65536");

                            t.HasCheckConstraint("ck_vector_builds_generation_id", "index_generation_id IS NULL OR length(index_generation_id) = 71 AND substr(index_generation_id, 1, 7) = 'idxgen-' AND substr(index_generation_id, 8) NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("ck_vector_builds_generation_state", "(status = 'Validated' AND index_generation_id IS NOT NULL AND validated_at_utc IS NOT NULL) OR (status <> 'Validated' AND index_generation_id IS NULL AND validated_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_vector_builds_status", "status IN ('Candidate', 'Validated', 'Failed')");

                            t.HasCheckConstraint("ck_vector_builds_validated_utc", "validated_at_utc IS NULL OR length(validated_at_utc) = 33 AND substr(validated_at_utc, -6) = '+00:00'");
                        });
                });

            modelBuilder.Entity("RagChallenge.Infrastructure.Persistence.VectorChunkRow", b =>
                {
                    b.Property<string>("CandidateBuildId")
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_build_id")
                        .UseCollation("BINARY");

                    b.Property<long>("ChunkOrdinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_ordinal");

                    b.Property<string>("ChunkDigest")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_digest")
                        .UseCollation("BINARY");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_text")
                        .UseCollation("BINARY");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id")
                        .UseCollation("BINARY");

                    b.Property<long>("DocumentVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_version");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("vector");

                    b.HasKey("CandidateBuildId", "ChunkOrdinal");

                    b.HasIndex("CandidateBuildId", "DocumentId", "DocumentVersion", "ChunkDigest")
                        .IsUnique();

                    b.ToTable("vector_chunks", null, t =>
                        {
                            t.HasCheckConstraint("ck_vector_chunks_digest", "length(chunk_digest) = 64 AND chunk_digest NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("ck_vector_chunks_document_version", "document_version > 0");

                            t.HasCheckConstraint("ck_vector_chunks_ordinal", "chunk_ordinal >= 0");

                            t.HasCheckConstraint("ck_vector_chunks_text", "length(chunk_text) BETWEEN 1 AND 1048576");

                            t.HasCheckConstraint("ck_vector_chunks_vector", "length(vector) > 0 AND length(vector) % 4 = 0");
                        });
                });

            modelBuilder.Entity("RagChallenge.Infrastructure.Persistence.VectorChunkRow", b =>
                {
                    b.HasOne("RagChallenge.Infrastructure.Persistence.VectorBuildRow", null)
                        .WithMany()
                        .HasForeignKey("CandidateBuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
